# -------------------------------- Qt --------------------------------

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core)
set(CMAKE_AUTOMOC TRUE)


# For FreeCAD 0.20, pegged to Ubuntu 18.04 LTS:
if((${Qt5Core_VERSION} VERSION_LESS "5.9") AND (NOT Qt6_FOUND))
    message (FATAL_ERROR "FreeCAD v0.20 requires Qt5 5.9 or later")
endif()
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Network)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Xml)
#find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS XmlPatterns)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS )
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Concurrent)
if(Qt6_FOUND)
    find_package(Qt6 COMPONENTS Core5Compat REQUIRED)  
endif()
if(BUILD_GUI)
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS PrintSupport)
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS OpenGL)
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Svg)
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS UiTools)
    if (BUILD_WEB)
        find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS WebEngineWidgets)
    endif()
    if(MSVC)
      find_package(Qt${QT_VERSION_MAJOR}WinExtras QUIET)
    endif()
endif(BUILD_GUI)
